services:
  spring-boot-app:
    image: anasortukov/spring_app
    #    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres
    environment:
      POSTGRES_DB: bookshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
